# Generated by Django 5.1.6 on 2026-09-13 12:17

import apps.core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('shopify_orders_count', models.IntegerField(blank=True, null=True)),
                ('shopify_total_spent', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(db_index=True, help_text="The order name as shown to the customer, e.g. '#1042'", max_length=50)),
                ('order_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('placed_at', models.DateTimeField(db_index=True)),
                ('placed_on', models.DateField(db_index=True, help_text='Local calendar day of placed_at, stored so date grouping stays indexable')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('financial_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorised'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voided', 'Voided'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('fulfilment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partial', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('restocked', 'Restocked'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('total_discounts', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total discounted across the order, as a positive amount', max_digits=12)),
                ('shipping_charged', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='What the customer paid for postage', max_digits=12)),
                ('total_tax', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='What the customer was charged in total', max_digits=12)),
                ('payment_fee', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Actual processing fee, when the payment provider reports it. Null means unknown, and profit will fall back to an estimate and say so.', max_digits=12, null=True)),
                ('is_test', models.BooleanField(db_index=True, default=False)),
                ('source_name', models.CharField(blank=True, max_length=60)),
                ('shipping_country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('discount_codes', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict, help_text="Shopify's payload as received, so nothing is lost in translation")),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.customer')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(help_text='Product title as sold', max_length=300)),
                ('variant_title', models.CharField(blank=True, max_length=300)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', apps.core.models.MoneyField(decimal_places=2, help_text='Price per unit before discount', max_digits=12)),
                ('discount_amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Discount allocated to this line, as a positive amount', max_digits=12)),
                ('tax_amount', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost_override', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Actual unit cost for this line, if known. Overrides the supplier price list, which is only ever an estimate of what was really paid.', max_digits=12, null=True)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.order')),
                ('product', models.ForeignKey(blank=True, help_text='Denormalised from the variant so product analytics stay fast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('refunded_at', models.DateTimeField(db_index=True)),
                ('refunded_on', models.DateField(db_index=True, help_text='Local calendar day of refunded_at')),
                ('amount', apps.core.models.MoneyField(decimal_places=2, help_text='Total refunded, as a positive amount', max_digits=12)),
                ('shipping_refunded', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_refunded', apps.core.models.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('restocked', models.BooleanField(default=False, help_text='Whether stock came back, which affects whether the cost is recovered')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.order')),
            ],
            options={
                'ordering': ['-refunded_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', apps.core.models.QuantityField(decimal_places=3, default=Decimal('0'), help_text='Units refunded. Fractional to allow partial value refunds.', max_digits=12)),
                ('amount', apps.core.models.MoneyField(decimal_places=2, help_text='Amount refunded for this line, as a positive amount', max_digits=12)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_lines', to='sales.orderline')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.refund')),
            ],
            options={
                'ordering': ['refund', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placed_on', 'is_test'], name='sales_order_placed__6f69b1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-placed_at'], name='sales_order_placed__a11089_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['product'], name='sales_order_product_b07c29_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['variant'], name='sales_order_variant_0e10c8_idx'),
        ),
    ]
