# Generated by Django 5.1.6 on 2026-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('shopify', 'Shopify'), ('inkthreadable', 'Inkthreadable')], db_index=True, max_length=30)),
                ('resource', models.CharField(choices=[('products', 'Products'), ('orders', 'Orders'), ('all', 'All')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cursor', models.CharField(blank=True, help_text='Incremental watermark written on success (updated_at or since_id)', max_length=80)),
                ('records_seen', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['service', 'resource', '-started_at'], name='integration_service_85d567_idx')],
            },
        ),
    ]
