# Generated by Django 5.1.6 on 2026-09-13 11:41

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorisationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transactions_examined', models.IntegerField(default=0)),
                ('transactions_changed', models.IntegerField(default=0)),
                ('transactions_locked_skipped', models.IntegerField(default=0)),
                ('left_uncategorised', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('REVENUE', 'Revenue'), ('COGS', 'Cost of goods sold'), ('SHIPPING', 'Shipping & postage'), ('FEES', 'Payment & platform fees'), ('OPERATING', 'Operating expense'), ('DISTRIBUTION', 'Owner distribution (salary / tithe)'), ('TRANSFER', 'Internal transfer'), ('EXCLUDED', 'Excluded from reporting')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('legacy_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('colour', models.CharField(blank=True, help_text='Hex colour for charts, e.g. #4F46E5', max_length=7)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional label to describe this rule', max_length=120)),
                ('pattern', models.CharField(help_text='Text to match against the transaction', max_length=255)),
                ('match_type', models.CharField(choices=[('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Does not contain'), ('STARTS_WITH', 'Starts with'), ('ENDS_WITH', 'Ends with'), ('EXACT', 'Exactly equals'), ('REGEX', 'Matches regular expression')], default='CONTAINS', max_length=20)),
                ('match_field', models.CharField(choices=[('COUNTERPARTY', 'Counterparty name'), ('DESCRIPTION', 'Bank description'), ('NOTES', 'Notes / reference'), ('ANY_TEXT', 'Any text field')], default='ANY_TEXT', max_length=20)),
                ('amount_condition', models.CharField(choices=[('ANY', 'Any amount'), ('NEGATIVE', 'Money out only'), ('POSITIVE', 'Money in only')], default='ANY', max_length=10)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers are evaluated first. The first matching rule wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('match_count', models.IntegerField(default=0, editable=False)),
                ('last_matched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='finance.category')),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MONZO_CSV', 'Monzo CSV export'), ('LEGACY_TRANSACTIONS', 'Spreadsheet — Transactions sheet'), ('LEGACY_HISTORIC', 'Spreadsheet — Historic Data sheet'), ('MANUAL', 'Entered manually')], max_length=30)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rows_read', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_duplicate', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(choices=[('DUPLICATE_EXTERNAL_ID', 'Row repeats an already-imported bank transaction ID'), ('UNREADABLE_DATE', 'Date could not be read'), ('UNREADABLE_AMOUNT', 'Amount could not be read'), ('UNKNOWN_CATEGORY', 'Category label not recognised')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=10)),
                ('message', models.TextField()),
                ('occurred_on', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Tick once you have reviewed this and decided no action is needed')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='finance.importbatch')),
            ],
            options={
                'ordering': ['-created_at', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MONZO_CSV', 'Monzo CSV export'), ('LEGACY_TRANSACTIONS', 'Spreadsheet — Transactions sheet'), ('LEGACY_HISTORIC', 'Spreadsheet — Historic Data sheet'), ('MANUAL', 'Entered manually')], max_length=30)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, editable=False, help_text='Content hash used to detect duplicates across overlapping imports', max_length=64)),
                ('occurred_on', models.DateField(db_index=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.CharField(blank=True, help_text='Merchant or payee name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Raw bank narrative, unmodified')),
                ('notes', models.CharField(blank=True, help_text='Reference or notes from the bank export', max_length=500)),
                ('transaction_type', models.CharField(blank=True, help_text='e.g. Card payment, Faster payment', max_length=60)),
                ('bank_category', models.CharField(blank=True, help_text="The bank's own guess at a category. Informational only.", max_length=60)),
                ('amount', apps.core.models.MoneyField(decimal_places=2, help_text='Signed: positive is money in, negative is money out', max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('local_amount', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Original amount if the charge was not in GBP', max_digits=12, null=True)),
                ('local_currency', models.CharField(blank=True, max_length=3)),
                ('balance_after', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category_source', models.CharField(choices=[('UNCATEGORISED', 'Uncategorised'), ('RULE', 'Matched a rule'), ('MANUAL', 'Set manually'), ('IMPORTED', 'Imported from spreadsheet')], default='UNCATEGORISED', max_length=20)),
                ('is_category_locked', models.BooleanField(default=False, help_text='Protects a manually chosen category from being overwritten when rules are re-run')),
                ('internal_notes', models.TextField(blank=True, help_text='Your own notes. Never touched by an import.')),
                ('raw', models.JSONField(blank=True, default=dict, help_text='The complete original source row')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.bankaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='finance.categoryrule')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.importbatch')),
            ],
            options={
                'ordering': ['-occurred_on', '-pk'],
                'indexes': [models.Index(fields=['occurred_on', 'category'], name='finance_ban_occurre_49b7b1_idx'), models.Index(fields=['source'], name='finance_ban_source_c639cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'fingerprint'), name='unique_transaction_per_account')],
            },
        ),
    ]
