# Generated by Django 5.1.6 on 2026-09-13 13:15

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('supplier', '0002_productmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('shopify_day', 'Shopify sales day'), ('supplier_order', 'Supplier invoice'), ('manual', 'Linked by hand')], max_length=20)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed by me'), ('suggested', 'Suggested automatically')], db_index=True, default='suggested', max_length=20)),
                ('sale_on', models.DateField(blank=True, db_index=True, help_text='The Shopify sales day this payout covers (first day if several).', null=True)),
                ('extra_sale_dates', models.JSONField(blank=True, default=list, help_text='Further sales days when one payout covers a run of days.')),
                ('expected_amount', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='What the matcher thought would land, so a later drift is visible.', max_digits=12, null=True)),
                ('match_reason', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_link', to='finance.banktransaction')),
                ('supplier_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_links', to='supplier.supplierorder')),
            ],
            options={
                'ordering': ['-bank_transaction__occurred_on', '-pk'],
            },
        ),
    ]
