# Generated by Django 5.1.6 on 2026-09-13 12:17

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_reference', models.CharField(help_text="Inkthreadable's order reference", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('placed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('product_cost', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Total charged for the items, as a positive amount', max_digits=12, null=True)),
                ('shipping_cost', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Total charged for postage, as a positive amount', max_digits=12, null=True)),
                ('tax', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('shipping_country', models.CharField(blank=True, max_length=2)),
                ('raw', models.JSONField(blank=True, default=dict, help_text="The supplier's response as received, kept for auditing")),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='The Shopify order this fulfils, once matched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to='sales.order')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.CharField(blank=True, db_index=True, help_text="Inkthreadable's identifier, when the API provides one", max_length=64)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(blank=True, db_index=True, help_text="e.g. 'Stanley/Stella', 'Gildan'", max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supplier_id__gt', '')), fields=('supplier_id',), name='unique_supplier_product_id')],
            },
        ),
        migrations.CreateModel(
            name='SupplierVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('size', models.CharField(blank=True, db_index=True, max_length=40)),
                ('colour', models.CharField(blank=True, db_index=True, max_length=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='supplier.supplierproduct')),
            ],
            options={
                'ordering': ['product__name', 'colour', 'size'],
            },
        ),
        migrations.CreateModel(
            name='SupplierVariantCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_cost', apps.core.models.MoneyField(decimal_places=2, help_text='Print and blank cost per unit, excluding shipping', max_digits=12)),
                ('effective_from', models.DateField(db_index=True, help_text='First date this cost applied. Orders before this use the previous cost.')),
                ('source', models.CharField(choices=[('api', 'Supplier API'), ('manual', 'Entered manually'), ('invoice', 'Read from an invoice')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('supplier_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='supplier.suppliervariant')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='VariantMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed by me'), ('suggested', 'Suggested automatically'), ('uncertain', 'Uncertain — needs review')], db_index=True, default='suggested', max_length=20)),
                ('cost_override', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text="Use this unit cost instead of the supplier's price list. For when you know the real cost and the catalogue is wrong or missing.", max_digits=12, null=True)),
                ('match_reason', models.CharField(blank=True, help_text='How this mapping was arrived at, for auditing automatic matches', max_length=300)),
                ('note', models.TextField(blank=True)),
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mapping', to='catalog.productvariant')),
                ('supplier_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='supplier.suppliervariant')),
            ],
            options={
                'ordering': ['product_variant__product__title', 'product_variant__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='suppliervariant',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_id__gt', '')), fields=('supplier_id',), name='unique_supplier_variant_id'),
        ),
        migrations.AddConstraint(
            model_name='suppliervariantcost',
            constraint=models.UniqueConstraint(fields=('supplier_variant', 'effective_from'), name='unique_cost_per_variant_per_date'),
        ),
    ]
