# Generated by Django 5.1.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "no_supplier",
                    models.BooleanField(
                        default=False,
                        help_text="Digital or otherwise not fulfilled by Inkthreadable. Cost is zero.",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed by me"),
                            ("suggested", "Suggested automatically"),
                            ("uncertain", "Uncertain — needs review"),
                        ],
                        db_index=True,
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("match_reason", models.CharField(blank=True, max_length=300)),
                ("note", models.TextField(blank=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_product_mapping",
                        to="catalog.product",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_mappings",
                        to="supplier.supplierproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product__title"],
            },
        ),
    ]
