# Generated by Django 5.1.6 on 2026-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_productmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Inkthreadable has phased this blank out. Historical costs stay; new orders cannot assume it is still available.'),
        ),
    ]
