# Generated by Django 5.1.6 on 2026-09-13 12:17

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, help_text="Shopify's global ID. Kept so syncing never duplicates a product.", max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('handle', models.SlugField(blank=True, max_length=300)),
                ('product_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['product_type', 'status'], name='catalog_pro_product_a883d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('colour', models.CharField(default='#6366f1', help_text='Hex colour used for this group in charts', max_length=7)),
                ('sort_order', models.IntegerField(default=100)),
                ('auto_match_product_types', models.CharField(blank=True, help_text="Comma-separated Shopify product types that should join this group automatically, e.g. 'T-Shirt, Tee'. Case-insensitive.", max_length=300)),
                ('products', models.ManyToManyField(blank=True, related_name='groups', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(blank=True, help_text="Shopify's variant title, e.g. 'Black / L'", max_length=300)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('position', models.IntegerField(default=1)),
                ('price', apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Current list price. Historical orders keep their own price.', max_digits=12, null=True)),
                ('compare_at_price', apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Raw option names and values as Shopify supplied them')),
                ('size', models.CharField(blank=True, db_index=True, help_text='Normalised size code, derived from options', max_length=40)),
                ('colour', models.CharField(blank=True, db_index=True, help_text='Normalised colour name, derived from options', max_length=60)),
                ('inventory_quantity', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product__title', 'position'],
                'indexes': [models.Index(fields=['product', 'size'], name='catalog_pro_product_b2756c_idx'), models.Index(fields=['product', 'colour'], name='catalog_pro_product_c3d36e_idx')],
            },
        ),
    ]
